export { default as Accordion } from "./accordion/accordion";
export { default as Carrousel } from "./carrousel/carrousel";
export { default as Contact } from "./contact/contact";
export { default as Events } from "./events/events";
// export { default as Footer } from "./footer/footer";
export { default as NavBar } from "./nav/nav";
export { default as Hero } from "./hero/hero";
export { default as Banner } from "./banner/banner";
export { default as Platform } from "./platform/platform";
export { default as Services } from "./services/services";
